### ISSUE TITLE
Not working on Embulk v0.8.15?

### ISSUE THREAD

**Issue by bcipolli** [mikoto2000/embulk-input-salesforce_bulk#4]
I am receiving an error:
`Caused by: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
`
![image](https://cloud.githubusercontent.com/assets/4072455/21081623/b9c8c89c-bf7f-11e6-9bca-94d4e93db1f8.png)

My yaml file is as follows (values get replaced in a string.format() call). I am confident that the formatting of the YAML is good, and that the output connector works (I use the same code for mongodb/mysql inputs).

Any help would be appreciated!
```
in:
  type: salesforce_bulk
  userName: {SALESFORCE_USERNAME}
  password: "{SALESFORCE_PASSWORD}"
  authEndpointUrl: https://login.salesforce.com/services/Soap/u/34.0
  objectType: Account
  pollingIntervalMillisecond: 5000
  querySelectFrom: SELECT Id,Name,LastModifiedDate FROM Account
  queryWhere: Name like '%a%'
  queryOrder: Name desc
  columns:
  - {{type: string, name: Id}}
  - {{type: string, name: Name}}
  - {{type: timestamp, name: LastModifiedDate, format: '%FT%T.%L%Z'}}

out:
  type: redshift
  host: {REDSHIFT_HOST}
  port: {REDSHIFT_PORT}
  user: {REDSHIFT_USERNAME}
  password: "{REDSHIFT_PASSWORD}"
  database: {REDSHIFT_DATABASE}
  schema: {REDSHIFT_SCHEMA}
  table: {table_name}
  access_key_id: {AWS_ACCESS_KEY}
  secret_access_key: {AWS_SECRET_ACCESS_KEY}
  iam_user_name: {AWS_IAM_USERNAME}
  s3_bucket: insights-etl
  s3_key_prefix: temp/redshift
  mode: replace
```
